### ISSUE TITLE
add new LED mode and "okay google"

### ISSUE THREAD

**Issue by Derodin** [toblum/McLighting#157]
Hello:

**New LED mode:**
Is it possible to add a mode that allows only certain LEDs to be lit?
As an example: _I have 300 LEDs, but only those between 150 to 200 LED light up_.
Where do I have to set the mode or add and how would the example code?

**HomeAssist:**
How exactly do I have to go this with "Okay Google" heading?

greetings
DerOdin

**Comment by debsahu** [comment]
See MQTT API in wiki. `R[rangstart_led][rangend_led][hexrgb]R[rangstart_led][rangend_led][hexrgb]R[rangstart_led][rangend_led][hexrgb] [...]`

Since this is a MQTT JSON light on Home Assistant, if you have Google Assistant setup according to https://www.home-assistant.io/components/google_assistant/ you can say "Hello Google, change xyz light to Green" etc.

**Comment by Derodin** [comment]
Thanks :)
