### ISSUE TITLE
MQTT-Status / Module Status

### ISSUE THREAD

**Issue by ozett** [toblum/McLighting#298]
i tried your firmware: its great.

as i newbie, i am missing some information about the running status.
at least at tasmota/sonoff there is a textpage. 
Maybe you want to code this a a new feature?

![image](https://user-images.githubusercontent.com/5937811/50343936-33a8a880-0529-11e9-93ea-6d05e21619aa.png)

i was trying to check the mqtt status, and saw different topis on console.
is this by design? or a bug?

![image](https://user-images.githubusercontent.com/5937811/50343910-1542ad00-0529-11e9-97ed-a1def276f8da.png)

**Comment by toblum** [comment]
Hi @ozett,

having some more informations in the UI is definitely on the list.
There is at least an API endpoint that gives some configuration and runtime informations: http://<IP_ADRESS>/esp_status

And yes, the MQTT topics are there by design. Some of them are there if you enables homeassistant integration: https://github.com/toblum/McLighting/wiki/Homeassistant-integration

Regards
Tobias

**Comment by ozett** [comment]
just a sidenote: 

the homeassistant-mqtt-topis should not be there,
because i did _not_ enable it...

(think thats the purpose of enable/disable)

**Comment by debsahu** [comment]
What's your output of http://<IP_ADRESS>/esp_status

**Comment by ozett** [comment]
![image](https://user-images.githubusercontent.com/5937811/50421414-4aa80d00-083f-11e9-922e-da343edd331d.png)
