### ISSUE TITLE
Instant MQTT state return on received command

### ISSUE THREAD

**Issue by TECHNOFAB11** [toblum/McLighting#389]
So I'm using McLighting with HA since some months or so and every time I, for example, turned it on in HA, it took some time for HA to be sure that it's on. Tasmota for example does return the state instantly after it received a command, making it easy for HA to check if it worked.

Either that's a misconfiguration on my side, and only I have this problem, or it's a nice little feature you could please add :) It's a little bit annoying having to wait 1s to be able to control color etc 😅

**Comment by debsahu** [comment]
The 5s delay is intentional, so that ESP8266 doesn't reset every time someone spams the controls on HA. If you want what you say you need, please change all occurances of ha_send_data.once(5, tickerSendState); to ha_send_data.once(0, tickerSendState); in request_handlers.h, which I highly not recommend doing!
