### ISSUE TITLE
Built releases

### ISSUE THREAD

**Issue by deviousasti** [toblum/McLighting#63]
Would it be possible to have a release builds of the major versions on Github?
They do have a good releases feature.

I don't use the Arduino IDE, just the ESP Open SDK - but I would be really happy to see a binary that can be flashed to try it out.

**Comment by toblum** [comment]
Hi @deviousasti,

I also thought about this, but the problem is that the number of LEDs and the name of the device (along with other settings) is part of the code and I didn't manage so far to make this dynamic. So a release would always work for a given number of LEDs and a static hostname. And that's not too useful.

If anyone has an idea how to solve this, this would be great.

Regards
Tobias
